# Name : 
    farers abbas 

# Gmail : 
    faresabbas.edu@gmail.com

# 1 - read data (train-test)

In [1]:
train_data = '../input/house-prices-advanced-regression-techniques/train.csv'

In [2]:
# import lib 
import pandas as pd 

# load data 
train_df=pd.read_csv(train_data)

In [3]:
train_df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
# show head and tail of data 
train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
train_df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [6]:
# show data columns name 
train_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [7]:
test_data = '../input/house-prices-advanced-regression-techniques/test.csv'

In [8]:
# load data 
test_df=pd.read_csv(test_data)

In [9]:
test_df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [10]:
# describing data
train_df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [11]:
# describing data
test_df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
count,1459.000000,1459.000000,1232.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1444.000000,1458.000000,...,1458.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,2190.000000,57.378341,68.580357,9819.161069,6.078821,5.553804,1971.357779,1983.662783,100.709141,439.203704,...,472.768861,93.174777,48.313914,24.243317,1.794380,17.064428,1.744345,58.167923,6.104181,2007.769705
std,421.321334,42.746880,22.376841,4955.517327,1.436812,1.113740,30.390071,21.130467,177.625900,455.268042,...,217.048611,127.744882,68.883364,67.227765,20.207842,56.609763,30.491646,630.806978,2.722432,1.301740
min,1461.000000,20.000000,21.000000,1470.000000,1.000000,1.000000,1879.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000
25%,1825.500000,20.000000,58.000000,7391.000000,5.000000,5.000000,1953.000000,1963.000000,0.000000,0.000000,...,318.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000
50%,2190.000000,50.000000,67.000000,9399.000000,6.000000,5.000000,1973.000000,1992.000000,0.000000,350.500000,...,480.000000,0.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000
75%,2554.500000,70.000000,80.000000,11517.500000,7.000000,6.000000,2001.000000,2004.000000,164.000000,753.500000,...,576.000000,168.000000,72.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000
max,2919.000000,190.000000,200.000000,56600.000000,10.000000,9.000000,2010.000000,2010.000000,1290.000000,4010.000000,...,1488.000000,1424.000000,742.000000,1012.000000,360.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000

In [12]:
# info 
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [13]:
# info 
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     1443 non-null   object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [14]:
traindata = train_df.drop(['Alley','PoolQC','Fence','MiscFeature'],axis=1)

In [15]:
traindata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 77 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     1452 non-null   object
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1423 non-null   object
 30  BsmtCond       1423 non-null   object
 31  BsmtExposure   1422 non-null   object
 32  BsmtFinType1   1423 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1422 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    object
 57  GarageType     1379 non-null   object
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   object
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1379 non-null   object
 63  GarageCond     1379 non-null   object
 64  PavedDrive     1460 non-null   object
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  MiscVal        1460 non-null   int64
 72  MoSold         1460 non-null   int64
 73  YrSold         1460 non-null   int64
 74  SaleType       1460 non-null   object
 75  SaleCondition  1460 non-null   object
 76  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(39)
memory usage: 878.4+ KB

In [16]:
testdata = test_df.drop(['Alley','PoolQC','Fence','MiscFeature'],axis=1)

In [17]:
testdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   LotShape       1459 non-null   object
 7   LandContour    1459 non-null   object
 8   Utilities      1457 non-null   object
 9   LotConfig      1459 non-null   object
 10  LandSlope      1459 non-null   object
 11  Neighborhood   1459 non-null   object
 12  Condition1     1459 non-null   object
 13  Condition2     1459 non-null   object
 14  BldgType       1459 non-null   object
 15  HouseStyle     1459 non-null   object
 16  OverallQual    1459 non-null   int64
 17  OverallCond    1459 non-null   int64
 18  YearBuilt      1459 non-null   int64
 19  YearRemodAdd   1459 non-null   int64
 20  RoofStyle      1459 non-null   object
 21  RoofMatl       1459 non-null   object
 22  Exterior1st    1458 non-null   object
 23  Exterior2nd    1458 non-null   object
 24  MasVnrType     1443 non-null   object
 25  MasVnrArea     1444 non-null   float64
 26  ExterQual      1459 non-null   object
 27  ExterCond      1459 non-null   object
 28  Foundation     1459 non-null   object
 29  BsmtQual       1415 non-null   object
 30  BsmtCond       1414 non-null   object
 31  BsmtExposure   1415 non-null   object
 32  BsmtFinType1   1417 non-null   object
 33  BsmtFinSF1     1458 non-null   float64
 34  BsmtFinType2   1417 non-null   object
 35  BsmtFinSF2     1458 non-null   float64
 36  BsmtUnfSF      1458 non-null   float64
 37  TotalBsmtSF    1458 non-null   float64
 38  Heating        1459 non-null   object
 39  HeatingQC      1459 non-null   object
 40  CentralAir     1459 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1459 non-null   int64
 43  2ndFlrSF       1459 non-null   int64
 44  LowQualFinSF   1459 non-null   int64
 45  GrLivArea      1459 non-null   int64
 46  BsmtFullBath   1457 non-null   float64
 47  BsmtHalfBath   1457 non-null   float64
 48  FullBath       1459 non-null   int64
 49  HalfBath       1459 non-null   int64
 50  BedroomAbvGr   1459 non-null   int64
 51  KitchenAbvGr   1459 non-null   int64
 52  KitchenQual    1458 non-null   object
 53  TotRmsAbvGrd   1459 non-null   int64
 54  Functional     1457 non-null   object
 55  Fireplaces     1459 non-null   int64
 56  FireplaceQu    729 non-null    object
 57  GarageType     1383 non-null   object
 58  GarageYrBlt    1381 non-null   float64
 59  GarageFinish   1381 non-null   object
 60  GarageCars     1458 non-null   float64
 61  GarageArea     1458 non-null   float64
 62  GarageQual     1381 non-null   object
 63  GarageCond     1381 non-null   object
 64  PavedDrive     1459 non-null   object
 65  WoodDeckSF     1459 non-null   int64
 66  OpenPorchSF    1459 non-null   int64
 67  EnclosedPorch  1459 non-null   int64
 68  3SsnPorch      1459 non-null   int64
 69  ScreenPorch    1459 non-null   int64
 70  PoolArea       1459 non-null   int64
 71  MiscVal        1459 non-null   int64
 72  MoSold         1459 non-null   int64
 73  YrSold         1459 non-null   int64
 74  SaleType       1458 non-null   object
 75  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(39)
memory usage: 866.4+ KB

In [18]:
traindata

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [19]:
objList = traindata.select_dtypes(include = "object").columns
print (objList)

Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition'],
      dtype='object')

In [20]:
#Label Encoding for object to numeric conversion
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feat in objList:
    traindata[feat] = le.fit_transform(traindata[feat].astype(str))

print (traindata.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 77 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   int64
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   int64
 6   LotShape       1460 non-null   int64
 7   LandContour    1460 non-null   int64
 8   Utilities      1460 non-null   int64
 9   LotConfig      1460 non-null   int64
 10  LandSlope      1460 non-null   int64
 11  Neighborhood   1460 non-null   int64
 12  Condition1     1460 non-null   int64
 13  Condition2     1460 non-null   int64
 14  BldgType       1460 non-null   int64
 15  HouseStyle     1460 non-null   int64
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   int64
 21  RoofMatl       1460 non-null   int64
 22  Exterior1st    1460 non-null   int64
 23  Exterior2nd    1460 non-null   int64
 24  MasVnrType     1460 non-null   int64
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   int64
 27  ExterCond      1460 non-null   int64
 28  Foundation     1460 non-null   int64
 29  BsmtQual       1460 non-null   int64
 30  BsmtCond       1460 non-null   int64
 31  BsmtExposure   1460 non-null   int64
 32  BsmtFinType1   1460 non-null   int64
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1460 non-null   int64
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   int64
 39  HeatingQC      1460 non-null   int64
 40  CentralAir     1460 non-null   int64
 41  Electrical     1460 non-null   int64
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   int64
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   int64
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    1460 non-null   int64
 57  GarageType     1460 non-null   int64
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1460 non-null   int64
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1460 non-null   int64
 63  GarageCond     1460 non-null   int64
 64  PavedDrive     1460 non-null   int64
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  MiscVal        1460 non-null   int64
 72  MoSold         1460 non-null   int64
 73  YrSold         1460 non-null   int64
 74  SaleType       1460 non-null   int64
 75  SaleCondition  1460 non-null   int64
 76  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(74)
memory usage: 878.4 KB
None

In [21]:
traindata

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,3,3,0,4,...,0,0,0,0,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,3,3,0,2,...,0,0,0,0,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,0,3,0,4,...,0,0,0,0,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,0,3,0,0,...,272,0,0,0,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,0,3,0,2,...,0,0,0,0,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,3,3,0,4,...,0,0,0,0,0,8,2007,8,4,175000
1456,1457,20,3,85.0,13175,1,3,3,0,4,...,0,0,0,0,0,2,2010,8,4,210000
1457,1458,70,3,66.0,9042,1,3,3,0,4,...,0,0,0,0,2500,5,2010,8,4,266500
1458,1459,20,3,68.0,9717,1,3,3,0,4,...,112,0,0,0,0,4,2010,8,4,142125
1459,1460,20,3,75.0,9937,1,3,3,0,4,...,0,0,0,0,0,6,2008,8,4,147500

In [22]:
#Label Encoding for object to numeric conversion
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feat in objList:
    testdata[feat] = le.fit_transform(testdata[feat].astype(str))

print (testdata.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1459 non-null   int64
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   int64
 6   LotShape       1459 non-null   int64
 7   LandContour    1459 non-null   int64
 8   Utilities      1459 non-null   int64
 9   LotConfig      1459 non-null   int64
 10  LandSlope      1459 non-null   int64
 11  Neighborhood   1459 non-null   int64
 12  Condition1     1459 non-null   int64
 13  Condition2     1459 non-null   int64
 14  BldgType       1459 non-null   int64
 15  HouseStyle     1459 non-null   int64
 16  OverallQual    1459 non-null   int64
 17  OverallCond    1459 non-null   int64
 18  YearBuilt      1459 non-null   int64
 19  YearRemodAdd   1459 non-null   int64
 20  RoofStyle      1459 non-null   int64
 21  RoofMatl       1459 non-null   int64
 22  Exterior1st    1459 non-null   int64
 23  Exterior2nd    1459 non-null   int64
 24  MasVnrType     1459 non-null   int64
 25  MasVnrArea     1444 non-null   float64
 26  ExterQual      1459 non-null   int64
 27  ExterCond      1459 non-null   int64
 28  Foundation     1459 non-null   int64
 29  BsmtQual       1459 non-null   int64
 30  BsmtCond       1459 non-null   int64
 31  BsmtExposure   1459 non-null   int64
 32  BsmtFinType1   1459 non-null   int64
 33  BsmtFinSF1     1458 non-null   float64
 34  BsmtFinType2   1459 non-null   int64
 35  BsmtFinSF2     1458 non-null   float64
 36  BsmtUnfSF      1458 non-null   float64
 37  TotalBsmtSF    1458 non-null   float64
 38  Heating        1459 non-null   int64
 39  HeatingQC      1459 non-null   int64
 40  CentralAir     1459 non-null   int64
 41  Electrical     1459 non-null   int64
 42  1stFlrSF       1459 non-null   int64
 43  2ndFlrSF       1459 non-null   int64
 44  LowQualFinSF   1459 non-null   int64
 45  GrLivArea      1459 non-null   int64
 46  BsmtFullBath   1457 non-null   float64
 47  BsmtHalfBath   1457 non-null   float64
 48  FullBath       1459 non-null   int64
 49  HalfBath       1459 non-null   int64
 50  BedroomAbvGr   1459 non-null   int64
 51  KitchenAbvGr   1459 non-null   int64
 52  KitchenQual    1459 non-null   int64
 53  TotRmsAbvGrd   1459 non-null   int64
 54  Functional     1459 non-null   int64
 55  Fireplaces     1459 non-null   int64
 56  FireplaceQu    1459 non-null   int64
 57  GarageType     1459 non-null   int64
 58  GarageYrBlt    1381 non-null   float64
 59  GarageFinish   1459 non-null   int64
 60  GarageCars     1458 non-null   float64
 61  GarageArea     1458 non-null   float64
 62  GarageQual     1459 non-null   int64
 63  GarageCond     1459 non-null   int64
 64  PavedDrive     1459 non-null   int64
 65  WoodDeckSF     1459 non-null   int64
 66  OpenPorchSF    1459 non-null   int64
 67  EnclosedPorch  1459 non-null   int64
 68  3SsnPorch      1459 non-null   int64
 69  ScreenPorch    1459 non-null   int64
 70  PoolArea       1459 non-null   int64
 71  MiscVal        1459 non-null   int64
 72  MoSold         1459 non-null   int64
 73  YrSold         1459 non-null   int64
 74  SaleType       1459 non-null   int64
 75  SaleCondition  1459 non-null   int64
dtypes: float64(11), int64(65)
memory usage: 866.4 KB
None

In [23]:
X = traindata.drop(['SalePrice'],axis=1)
y = traindata.SalePrice

In [24]:
#Import Libraries
from sklearn.impute import SimpleImputer
import numpy as np
#----------------------------------------------------

#----------------------------------------------------
# Cleaning data

'''
impute.SimpleImputer(missing_values=nan, strategy='mean’, fill_value=None, verbose=0, copy=True)
'''


ImputedModule = SimpleImputer(missing_values = np.nan, strategy ='mean')
ImputedX = ImputedModule.fit(X)
X = ImputedX.transform(X)


# X Data
print('X Data is \n' , X[:10])

#y Data
#print('y Data is \n' , y[:10])

X Data is
 [[1.00000000e+00 6.00000000e+01 3.00000000e+00 6.50000000e+01
  8.45000000e+03 1.00000000e+00 3.00000000e+00 3.00000000e+00
  0.00000000e+00 4.00000000e+00 0.00000000e+00 5.00000000e+00
  2.00000000e+00 2.00000000e+00 0.00000000e+00 5.00000000e+00
  7.00000000e+00 5.00000000e+00 2.00300000e+03 2.00300000e+03
  1.00000000e+00 1.00000000e+00 1.20000000e+01 1.30000000e+01
  1.00000000e+00 1.96000000e+02 2.00000000e+00 4.00000000e+00
  2.00000000e+00 2.00000000e+00 3.00000000e+00 3.00000000e+00
  2.00000000e+00 7.06000000e+02 5.00000000e+00 0.00000000e+00
  1.50000000e+02 8.56000000e+02 1.00000000e+00 0.00000000e+00
  1.00000000e+00 4.00000000e+00 8.56000000e+02 8.54000000e+02
  0.00000000e+00 1.71000000e+03 1.00000000e+00 0.00000000e+00
  2.00000000e+00 1.00000000e+00 3.00000000e+00 1.00000000e+00
  2.00000000e+00 8.00000000e+00 6.00000000e+00 0.00000000e+00
  5.00000000e+00 1.00000000e+00 2.00300000e+03 1.00000000e+00
  2.00000000e+00 5.48000000e+02 4.00000000e+00 4.00000000e+00
  2.00000000e+00 0.00000000e+00 6.10000000e+01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.00000000e+00 2.00800000e+03 8.00000000e+00 4.00000000e+00]
 [2.00000000e+00 2.00000000e+01 3.00000000e+00 8.00000000e+01
  9.60000000e+03 1.00000000e+00 3.00000000e+00 3.00000000e+00
  0.00000000e+00 2.00000000e+00 0.00000000e+00 2.40000000e+01
  1.00000000e+00 2.00000000e+00 0.00000000e+00 2.00000000e+00
  6.00000000e+00 8.00000000e+00 1.97600000e+03 1.97600000e+03
  1.00000000e+00 1.00000000e+00 8.00000000e+00 8.00000000e+00
  2.00000000e+00 0.00000000e+00 3.00000000e+00 4.00000000e+00
  1.00000000e+00 2.00000000e+00 3.00000000e+00 1.00000000e+00
  0.00000000e+00 9.78000000e+02 5.00000000e+00 0.00000000e+00
  2.84000000e+02 1.26200000e+03 1.00000000e+00 0.00000000e+00
  1.00000000e+00 4.00000000e+00 1.26200000e+03 0.00000000e+00
  0.00000000e+00 1.26200000e+03 0.00000000e+00 1.00000000e+00
  2.00000000e+00 0.00000000e+00 3.00000000e+00 1.00000000e+00
  3.00000000e+00 6.00000000e+00 6.00000000e+00 1.00000000e+00
  4.00000000e+00 1.00000000e+00 1.97600000e+03 1.00000000e+00
  2.00000000e+00 4.60000000e+02 4.00000000e+00 4.00000000e+00
  2.00000000e+00 2.98000000e+02 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  5.00000000e+00 2.00700000e+03 8.00000000e+00 4.00000000e+00]
 [3.00000000e+00 6.00000000e+01 3.00000000e+00 6.80000000e+01
  1.12500000e+04 1.00000000e+00 0.00000000e+00 3.00000000e+00
  0.00000000e+00 4.00000000e+00 0.00000000e+00 5.00000000e+00
  2.00000000e+00 2.00000000e+00 0.00000000e+00 5.00000000e+00
  7.00000000e+00 5.00000000e+00 2.00100000e+03 2.00200000e+03
  1.00000000e+00 1.00000000e+00 1.20000000e+01 1.30000000e+01
  1.00000000e+00 1.62000000e+02 2.00000000e+00 4.00000000e+00
  2.00000000e+00 2.00000000e+00 3.00000000e+00 2.00000000e+00
  2.00000000e+00 4.86000000e+02 5.00000000e+00 0.00000000e+00
  4.34000000e+02 9.20000000e+02 1.00000000e+00 0.00000000e+00
  1.00000000e+00 4.00000000e+00 9.20000000e+02 8.66000000e+02
  0.00000000e+00 1.78600000e+03 1.00000000e+00 0.00000000e+00
  2.00000000e+00 1.00000000e+00 3.00000000e+00 1.00000000e+00
  2.00000000e+00 6.00000000e+00 6.00000000e+00 1.00000000e+00
  4.00000000e+00 1.00000000e+00 2.00100000e+03 1.00000000e+00
  2.00000000e+00 6.08000000e+02 4.00000000e+00 4.00000000e+00
  2.00000000e+00 0.00000000e+00 4.20000000e+01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  9.00000000e+00 2.00800000e+03 8.00000000e+00 4.00000000e+00]
 [4.00000000e+00 7.00000000e+01 3.00000000e+00 6.00000000e+01
  9.55000000e+03 1.00000000e+00 0.00000000e+00 3.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 6.00000000e+00
  2.00000000e+00 2.00000000e+00 0.00000000e+00 5.00000000e+00
  7.00000000e+00 5.00000000e+00 1.91500000e+03 1.97000000e+03
  1.00000000e+00 1.00000000e+00 1.30000000e+01 1.50000000e+01
  2.00000000e+00 0.00000000e+00 3.00000000e+00 4.00000000e+00
  0.00000000e+00 3.00000000e+00 1.00000000e+00 3.00000000e+00
  0.00000000e+00 2.16000000e+02 5.00000000e+00 0.00000000e+00
  5.40000000e+02 7.56000000e+02 1.00000000e+00 2.00000000e+00
  1.00000000e+00 4.00000000e+00 9.61000000e+02 7.56000000e+02
  0.00000000e+00 1.71700000e+03 1.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 3.00000000e+00 1.00000000e+00
  2.00000000e+00 7.00000000e+00 6.00000000e+00 1.00000000e+00
  2.00000000e+00 5.00000000e+00 1.99800000e+03 2.00000000e+00
  3.00000000e+00 6.42000000e+02 4.00000000e+00 4.00000000e+00
  2.00000000e+00 0.00000000e+00 3.50000000e+01 2.72000000e+02
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.00000000e+00 2.00600000e+03 8.00000000e+00 0.00000000e+00]
 [5.00000000e+00 6.00000000e+01 3.00000000e+00 8.40000000e+01
  1.42600000e+04 1.00000000e+00 0.00000000e+00 3.00000000e+00
  0.00000000e+00 2.00000000e+00 0.00000000e+00 1.50000000e+01
  2.00000000e+00 2.00000000e+00 0.00000000e+00 5.00000000e+00
  8.00000000e+00 5.00000000e+00 2.00000000e+03 2.00000000e+03
  1.00000000e+00 1.00000000e+00 1.20000000e+01 1.30000000e+01
  1.00000000e+00 3.50000000e+02 2.00000000e+00 4.00000000e+00
  2.00000000e+00 2.00000000e+00 3.00000000e+00 0.00000000e+00
  2.00000000e+00 6.55000000e+02 5.00000000e+00 0.00000000e+00
  4.90000000e+02 1.14500000e+03 1.00000000e+00 0.00000000e+00
  1.00000000e+00 4.00000000e+00 1.14500000e+03 1.05300000e+03
  0.00000000e+00 2.19800000e+03 1.00000000e+00 0.00000000e+00
  2.00000000e+00 1.00000000e+00 4.00000000e+00 1.00000000e+00
  2.00000000e+00 9.00000000e+00 6.00000000e+00 1.00000000e+00
  4.00000000e+00 1.00000000e+00 2.00000000e+03 1.00000000e+00
  3.00000000e+00 8.36000000e+02 4.00000000e+00 4.00000000e+00
  2.00000000e+00 1.92000000e+02 8.40000000e+01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.20000000e+01 2.00800000e+03 8.00000000e+00 4.00000000e+00]
 [6.00000000e+00 5.00000000e+01 3.00000000e+00 8.50000000e+01
  1.41150000e+04 1.00000000e+00 0.00000000e+00 3.00000000e+00
  0.00000000e+00 4.00000000e+00 0.00000000e+00 1.10000000e+01
  2.00000000e+00 2.00000000e+00 0.00000000e+00 0.00000000e+00
  5.00000000e+00 5.00000000e+00 1.99300000e+03 1.99500000e+03
  1.00000000e+00 1.00000000e+00 1.20000000e+01 1.30000000e+01
  2.00000000e+00 0.00000000e+00 3.00000000e+00 4.00000000e+00
  5.00000000e+00 2.00000000e+00 3.00000000e+00 3.00000000e+00
  2.00000000e+00 7.32000000e+02 5.00000000e+00 0.00000000e+00
  6.40000000e+01 7.96000000e+02 1.00000000e+00 0.00000000e+00
  1.00000000e+00 4.00000000e+00 7.96000000e+02 5.66000000e+02
  0.00000000e+00 1.36200000e+03 1.00000000e+00 0.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  3.00000000e+00 5.00000000e+00 6.00000000e+00 0.00000000e+00
  5.00000000e+00 1.00000000e+00 1.99300000e+03 2.00000000e+00
  2.00000000e+00 4.80000000e+02 4.00000000e+00 4.00000000e+00
  2.00000000e+00 4.00000000e+01 3.00000000e+01 0.00000000e+00
  3.20000000e+02 0.00000000e+00 0.00000000e+00 7.00000000e+02
  1.00000000e+01 2.00900000e+03 8.00000000e+00 4.00000000e+00]
 [7.00000000e+00 2.00000000e+01 3.00000000e+00 7.50000000e+01
  1.00840000e+04 1.00000000e+00 3.00000000e+00 3.00000000e+00
  0.00000000e+00 4.00000000e+00 0.00000000e+00 2.10000000e+01
  2.00000000e+00 2.00000000e+00 0.00000000e+00 2.00000000e+00
  8.00000000e+00 5.00000000e+00 2.00400000e+03 2.00500000e+03
  1.00000000e+00 1.00000000e+00 1.20000000e+01 1.30000000e+01
  3.00000000e+00 1.86000000e+02 2.00000000e+00 4.00000000e+00
  2.00000000e+00 0.00000000e+00 3.00000000e+00 0.00000000e+00
  2.00000000e+00 1.36900000e+03 5.00000000e+00 0.00000000e+00
  3.17000000e+02 1.68600000e+03 1.00000000e+00 0.00000000e+00
  1.00000000e+00 4.00000000e+00 1.69400000e+03 0.00000000e+00
  0.00000000e+00 1.69400000e+03 1.00000000e+00 0.00000000e+00
  2.00000000e+00 0.00000000e+00 3.00000000e+00 1.00000000e+00
  2.00000000e+00 7.00000000e+00 6.00000000e+00 1.00000000e+00
  2.00000000e+00 1.00000000e+00 2.00400000e+03 1.00000000e+00
  2.00000000e+00 6.36000000e+02 4.00000000e+00 4.00000000e+00
  2.00000000e+00 2.55000000e+02 5.70000000e+01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  8.00000000e+00 2.00700000e+03 8.00000000e+00 4.00000000e+00]
 [8.00000000e+00 6.00000000e+01 3.00000000e+00 7.00499584e+01
  1.03820000e+04 1.00000000e+00 0.00000000e+00 3.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.40000000e+01
  4.00000000e+00 2.00000000e+00 0.00000000e+00 5.00000000e+00
  7.00000000e+00 6.00000000e+00 1.97300000e+03 1.97300000e+03
  1.00000000e+00 1.00000000e+00 6.00000000e+00 6.00000000e+00
  3.00000000e+00 2.40000000e+02 3.00000000e+00 4.00000000e+00
  1.00000000e+00 2.00000000e+00 3.00000000e+00 2.00000000e+00
  0.00000000e+00 8.59000000e+02 1.00000000e+00 3.20000000e+01
  2.16000000e+02 1.10700000e+03 1.00000000e+00 0.00000000e+00
  1.00000000e+00 4.00000000e+00 1.10700000e+03 9.83000000e+02
  0.00000000e+00 2.09000000e+03 1.00000000e+00 0.00000000e+00
  2.00000000e+00 1.00000000e+00 3.00000000e+00 1.00000000e+00
  3.00000000e+00 7.00000000e+00 6.00000000e+00 2.00000000e+00
  4.00000000e+00 1.00000000e+00 1.97300000e+03 1.00000000e+00
  2.00000000e+00 4.84000000e+02 4.00000000e+00 4.00000000e+00
  2.00000000e+00 2.35000000e+02 2.04000000e+02 2.28000000e+02
  0.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+02
  1.10000000e+01 2.00900000e+03 8.00000000e+00 4.00000000e+00]
 [9.00000000e+00 5.00000000e+01 4.00000000e+00 5.10000000e+01
  6.12000000e+03 1.00000000e+00 3.00000000e+00 3.00000000e+00
  0.00000000e+00 4.00000000e+00 0.00000000e+00 1.70000000e+01
  0.00000000e+00 2.00000000e+00 0.00000000e+00 0.00000000e+00
  7.00000000e+00 5.00000000e+00 1.93100000e+03 1.95000000e+03
  1.00000000e+00 1.00000000e+00 3.00000000e+00 1.50000000e+01
  2.00000000e+00 0.00000000e+00 3.00000000e+00 4.00000000e+00
  0.00000000e+00 3.00000000e+00 3.00000000e+00 3.00000000e+00
  5.00000000e+00 0.00000000e+00 5.00000000e+00 0.00000000e+00
  9.52000000e+02 9.52000000e+02 1.00000000e+00 2.00000000e+00
  1.00000000e+00 1.00000000e+00 1.02200000e+03 7.52000000e+02
  0.00000000e+00 1.77400000e+03 0.00000000e+00 0.00000000e+00
  2.00000000e+00 0.00000000e+00 2.00000000e+00 2.00000000e+00
  3.00000000e+00 8.00000000e+00 2.00000000e+00 2.00000000e+00
  4.00000000e+00 5.00000000e+00 1.93100000e+03 2.00000000e+00
  2.00000000e+00 4.68000000e+02 1.00000000e+00 4.00000000e+00
  2.00000000e+00 9.00000000e+01 0.00000000e+00 2.05000000e+02
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  4.00000000e+00 2.00800000e+03 8.00000000e+00 0.00000000e+00]
 [1.00000000e+01 1.90000000e+02 3.00000000e+00 5.00000000e+01
  7.42000000e+03 1.00000000e+00 3.00000000e+00 3.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 3.00000000e+00
  0.00000000e+00 0.00000000e+00 1.00000000e+00 1.00000000e+00
  5.00000000e+00 6.00000000e+00 1.93900000e+03 1.95000000e+03
  1.00000000e+00 1.00000000e+00 8.00000000e+00 8.00000000e+00
  2.00000000e+00 0.00000000e+00 3.00000000e+00 4.00000000e+00
  0.00000000e+00 3.00000000e+00 3.00000000e+00 3.00000000e+00
  2.00000000e+00 8.51000000e+02 5.00000000e+00 0.00000000e+00
  1.40000000e+02 9.91000000e+02 1.00000000e+00 0.00000000e+00
  1.00000000e+00 4.00000000e+00 1.07700000e+03 0.00000000e+00
  0.00000000e+00 1.07700000e+03 1.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 2.00000000e+00 2.00000000e+00
  3.00000000e+00 5.00000000e+00 6.00000000e+00 2.00000000e+00
  4.00000000e+00 1.00000000e+00 1.93900000e+03 1.00000000e+00
  1.00000000e+00 2.05000000e+02 2.00000000e+00 4.00000000e+00
  2.00000000e+00 0.00000000e+00 4.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 2.00800000e+03 8.00000000e+00 4.00000000e+00]]

In [25]:
ImputedModule_test = SimpleImputer(missing_values = np.nan, strategy ='mean')
ImputedTEST = ImputedModule_test.fit(testdata)
testdata = ImputedTEST.transform(testdata)

In [26]:
testdata

array([[1.461e+03, 2.000e+01, 2.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       [1.462e+03, 2.000e+01, 3.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       [1.463e+03, 6.000e+01, 3.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       ...,
       [2.917e+03, 2.000e+01, 3.000e+00, ..., 2.006e+03, 8.000e+00,
        0.000e+00],
       [2.918e+03, 8.500e+01, 3.000e+00, ..., 2.006e+03, 8.000e+00,
        4.000e+00],
       [2.919e+03, 6.000e+01, 3.000e+00, ..., 2.006e+03, 8.000e+00,
        4.000e+00]])

In [27]:
#Import Libraries
from sklearn.model_selection import train_test_split
#----------------------------------------------------

#----------------------------------------------------
#Splitting data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=44, shuffle =True)

#Splitted Data
#print('X_train shape is ' , X_train.shape)
#print('X_test shape is ' , X_test.shape)
#print('y_train shape is ' , y_train.shape)
#print('y_test shape is ' , y_test.shape)

In [28]:
#Import Libraries
from sklearn.svm import SVR

'''
sklearn.svm.SVR(kernel=’rbf’, degree=3, gamma=’auto_deprecated’, coef0=0.0, tol=0.001,
                C=1.0, epsilon=0.1, shrinking=True, cache_size=200, verbose=False,max_iter=-1)
'''

SVRModel = SVR(C = 1.0 ,epsilon=0.01,kernel = 'linear') # it also can be : linear, poly, rbf, sigmoid, precomputed
SVRModel.fit(X_train, y_train)

#Calculating Details
print('SVRModel Train Score is : ' , SVRModel.score(X_train, y_train))
print('SVRModel Test Score is : ' , SVRModel.score(X_test, y_test))
#print('----------------------------------------------------')

SVRModel Train Score is :  0.7309851461718628
SVRModel Test Score is :  0.8260694852059254

In [29]:
# #Calculating Prediction
y_pred = SVRModel.predict(testdata)

In [30]:
y_pred

array([135608.26199697, 179503.03382207, 201596.11656616, ...,
       197093.02427579, 119543.13005508, 229692.31142281])

In [31]:
sample_submisstion = pd.read_csv('../input/house-prices-advanced-regression-techniques/sample_submission.csv')

In [32]:
sample_submisstion

        Id      SalePrice
0     1461  169277.052498
1     1462  187758.393989
2     1463  183583.683570
3     1464  179317.477511
4     1465  150730.079977
...    ...            ...
1454  2915  167081.220949
1455  2916  164788.778231
1456  2917  219222.423400
1457  2918  184924.279659
1458  2919  187741.866657

[1459 rows x 2 columns]

In [33]:
sample_submisstion =sample_submisstion.drop(columns='SalePrice',axis=1)

In [34]:
sample_submisstion

        Id
0     1461
1     1462
2     1463
3     1464
4     1465
...    ...
1454  2915
1455  2916
1456  2917
1457  2918
1458  2919

[1459 rows x 1 columns]

In [35]:
submission=pd.DataFrame({'Id':sample_submisstion['Id'],'SalePrice':y_pred})
submission

        Id      SalePrice
0     1461  135608.261997
1     1462  179503.033822
2     1463  201596.116566
3     1464  201124.503093
4     1465  171256.899473
...    ...            ...
1454  2915   77331.654154
1455  2916   92500.191411
1456  2917  197093.024276
1457  2918  119543.130055
1458  2919  229692.311423

[1459 rows x 2 columns]

In [36]:
submission.to_csv('house-prices-advanced-regression-techniques.csv',index=None)